apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-zh-ghcr-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-image-signature
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - signed
      verifyImages:
        - imageReferences:
            - "ghcr.io/zahlenhelfer/docker-ghcr-gha-cosign-nginx/*"
          verifyDigest: true
          attestors:
            - entries:
                - keyless:
                    issuer: "https://token.actions.githubusercontent.com"
                    subjectRegExp: ^repo:zahlenhelfer/docker-ghcr-gha-cosign-nginx:.*
                    rekor:
                      url: "https://rekor.sigstore.dev"
